name: Gradle Dependency Submission

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/dependency_submission.yml'
      - 'build.gradle'
      - 'settings.gradle'
      - '**/gradle/**'

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up JDK
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          java-version: 25
          distribution: temurin
          cache: gradle
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_DEPENDENCY_GRAPH_JOB_CORRELATOR: master
          DEPENDENCY_GRAPH_INCLUDE_CONFIGURATIONS: runtimeClasspath
