name: Test and Build

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      prerelease:
        description: 'The release should be an experimental release'
        default: 'NO'
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17', '21', '25' ]
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
      - run: git config --global user.email "you@example.com"
      - run: git config --global user.name "Your Name"
      - name: Test with Gradle
        run: ./gradlew assemble check
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0
        if: github.ref == 'refs/heads/master'
        env:
          DEPENDENCY_GRAPH_INCLUDE_CONFIGURATIONS: none
  githubRelease:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          java-version: 21
          distribution: temurin
          cache: gradle
      - name: Release with Gradle
        run: ./gradlew githubRelease
        env:
          GITHUB_USER: "TWChennai"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          PRERELEASE: "${{ github.event.inputs.prerelease }}"
